const { withAppBuildGradle, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Mirrors the signing pattern EAS Build uses server-side
 * (https://docs.expo.dev/build-reference/android-builds/#configuring-gradle):
 *
 *   1. credentials.json at the project root is the single source of truth.
 *   2. android/app/eas-build.gradle reads it at Gradle-evaluation time and
 *      populates signingConfigs.release.
 *   3. android/app/build.gradle applies eas-build.gradle.
 *
 * Same credentials file works for `eas build` (cloud) and local Gradle.
 * If credentials.json is missing, signingConfigs.release has no storeFile —
 * `bundleRelease` fails loud instead of silently signing with the debug key.
 */

const EAS_BUILD_GRADLE = `// Generated by plugins/withEasBuildGradle. Do not edit by hand.
// Signs release builds with the keystore referenced in credentials.json.
import groovy.json.JsonSlurper

android {
    signingConfigs {
        release {
            def credentialsJson = file("../../credentials.json")
            if (credentialsJson.exists()) {
                def credentials = new JsonSlurper().parse(credentialsJson)
                storeFile file(credentials.android.keystore.keystorePath)
                storePassword credentials.android.keystore.keystorePassword
                keyAlias credentials.android.keystore.keyAlias
                keyPassword credentials.android.keystore.keyPassword
            }
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}
`;

const APPLY_LINE = 'apply from: "./eas-build.gradle"';

module.exports = function withEasBuildGradle(config) {
  // 1) Write android/app/eas-build.gradle on every prebuild.
  config = withDangerousMod(config, [
    'android',
    (cfg) => {
      const target = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'eas-build.gradle',
      );
      fs.writeFileSync(target, EAS_BUILD_GRADLE);
      return cfg;
    },
  ]);

  // 2) Append `apply from: "./eas-build.gradle"` to build.gradle (once).
  config = withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') return cfg;
    if (cfg.modResults.contents.includes(APPLY_LINE)) return cfg;
    cfg.modResults.contents = cfg.modResults.contents.trimEnd() + `\n\n${APPLY_LINE}\n`;
    return cfg;
  });

  return config;
};
